version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    networks:
      - nodeapp-network
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - nodeapp-network
networks:
  nodeapp-network:
    driver: bridge